version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: saas_db
    environment:
      MYSQL_DATABASE: saas_ot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
